# Generated by Django 5.2.1 on 2025-05-21 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "route_json",
                    models.TextField(
                        help_text="JSON with list of coordinates: [[lat, lng], [lat, lng], ...]"
                    ),
                ),
                (
                    "stops_json",
                    models.TextField(
                        help_text='JSON with list of stops: [{"name": "Stop A", "lat": ..., "lng": ...}, ...]'
                    ),
                ),
                (
                    "bus",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="bus.bus"
                    ),
                ),
            ],
        ),
    ]
